name: Version Checker
description: Check the version of the .csproj file
outputs:
  version: 
    description: Version
    value: ${{ steps.get-version.outputs.version }}
  timestamp: 
    description: Timestamp
    value: ${{ steps.timestamp.outputs.timestamp }}
runs:
  using: "composite"
  steps:
  
  - name: Check Project Version
    uses: kzrnm/get-net-sdk-project-versions-action@v1.1.2
    id: get-version
    with:
      proj-path: src/src.csproj
    
  - name: create timestamp
    id: timestamp
    run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
    shell: bash
      
